### ISSUE TITLE
ffmpeg-static-electron

### ISSUE THREAD

**Issue by shiffman** [shiffman/BodyBlock#2]
https://www.npmjs.com/package/ffmpeg-static-electron

Thanks to https://twitter.com/radiodario/status/1267604137648295936

**Comment by w3cj** [comment]
This package is maintained and recently updated: https://www.npmjs.com/package/ffmpeg-static

**Comment by shiffman** [comment]
Ah, thanks, this looks more up to date!

**Comment by joeyklee** [comment]
Closing this up now as this is now integrated. Many thanks @w3cj <3
