### ISSUE TITLE
Loading state

### ISSUE THREAD

**Issue by owenmcateer** [shiffman/BodyBlock#24]
State is required for when the App is initializing, upload or processing.
This should be a global state with a reusable busy indicator.
The loading state should lock the App and display the loading indicator animation from #19

**Comment by shiffman** [comment]
Thanks so much for this @owenmcateer! I'll leave this issue open and note the next step as proposed by @joeyklee to include this loading animation at other times, for example during the "process" or "save" steps.

**Comment by shiffman** [comment]
Ok, actually apologies this is covered in #19 so we can close this one for now!
